linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - goimports
    - revive
    - misspell
    - gofmt

linters-settings:
  goimports:
    local-prefixes: github.com/zlatkoc/go-aws-emf

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
