# Codecov configuration file
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%

ignore:
  - "pkg/emf/emf-format.go"  # Ignore generated file from coverage
  - "examples/**/*"          # Ignore example code from coverage
