name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
          CHANGELOG=$(git log --pretty=format:"* %s" $PREVIOUS_TAG..HEAD)
          echo "changelog=$CHANGELOG" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Changes
            ${{ env.changelog }}

            ## Usage
            ```go
            import "github.com/zlatkoc/go-aws-emf/pkg/emf"

            // Create EMF log with direct API
            emfLog := emf.NewEMFLog("MyService")
            emfLog.PutMetric("ProcessingTime", 100.0, emf.UnitMilliseconds)
            
            // Or use the builder pattern
            builder := emf.NewBuilder("MyService").
                WithNamespace("AWS/CustomMetrics").
                WithDimensions(map[string]string{"Service": "MyService"}).
                PutMetric("ProcessingTime", 100.0, emf.UnitMilliseconds)
            emfLog = builder.Build()
            
            // Serialize to JSON
            jsonBytes, _ := emfLog.MarshalJSON()
            ```
          draft: false
          prerelease: false
          files: |
            LICENSE
            README.md